# Generated by Django 3.1.6 on 2021-03-06 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('proposal_reason', models.TextField(null=True)),
                ('selected_proposal_condition', models.CharField(choices=[('selected', 'selected'), ('not_selected', 'not_selected'), ('not_verified', 'not_verified')], default='not_verified', max_length=12)),
                ('name', models.CharField(max_length=50, null=True)),
                ('git_url', models.URLField(null=True)),
                ('references', models.TextField(null=True)),
                ('tools', models.TextField(null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_reason', models.TextField(null=True)),
                ('selected_report_condition', models.CharField(choices=[('selected', 'selected'), ('not_selected', 'not_selected'), ('not_verified', 'not_verified')], default='not_verified', max_length=12)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
