# Generated by Django 3.1.6 on 2021-03-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/default/default.pdf', null=True, upload_to='proposals/'),
        ),
    ]
