# Generated by Django 3.1.6 on 2021-03-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210314_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_file',
            field=models.FileField(blank=True, default='default/default.pdf', null=True, upload_to='default/'),
        ),
    ]
