# Generated by Django 3.1.6 on 2021-03-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210314_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_file',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
    ]
